# Generated by cpp11: do not edit by hand

httpgd_ <- function(host, port, bg, width, height, pointsize, aliases, cors, token, webserver, silent, fix_text_width, extra_css) {
  .Call(`_httpgd_httpgd_`, host, port, bg, width, height, pointsize, aliases, cors, token, webserver, silent, fix_text_width, extra_css)
}

httpgd_state_ <- function(devnum) {
  .Call(`_httpgd_httpgd_state_`, devnum)
}

httpgd_random_token_ <- function(len) {
  .Call(`_httpgd_httpgd_random_token_`, len)
}

httpgd_svg_ <- function(devnum, page, width, height) {
  .Call(`_httpgd_httpgd_svg_`, devnum, page, width, height)
}

httpgd_remove_ <- function(devnum, page) {
  .Call(`_httpgd_httpgd_remove_`, devnum, page)
}

httpgd_clear_ <- function(devnum) {
  .Call(`_httpgd_httpgd_clear_`, devnum)
}
