# Generated by cpp11: do not edit by hand

httpgd_ <- function(devnum, host, port, cors, token, silent, wwwpath, title) {
  .Call(`_httpgd_httpgd_`, devnum, host, port, cors, token, silent, wwwpath, title)
}

httpgd_details_ <- function(devnum) {
  .Call(`_httpgd_httpgd_details_`, devnum)
}

httpgd_title_ <- function(devnum, title) {
  .Call(`_httpgd_httpgd_title_`, devnum, title)
}

httpgd_random_token_ <- function(len) {
  .Call(`_httpgd_httpgd_random_token_`, len)
}
