# Generated by cpp11: do not edit by hand

httpgd_ <- function(host, port, bg, width, height, pointsize, aliases, cors, token, webserver, silent, fix_text_width) {
  .Call("_httpgd_httpgd_", host, port, bg, width, height, pointsize, aliases, cors, token, webserver, silent, fix_text_width, PACKAGE = "httpgd")
}

httpgd_state_ <- function(devnum) {
  .Call("_httpgd_httpgd_state_", devnum, PACKAGE = "httpgd")
}

httpgd_random_token_ <- function(len) {
  .Call("_httpgd_httpgd_random_token_", len, PACKAGE = "httpgd")
}

httpgd_svg_ <- function(devnum, page, width, height) {
  .Call("_httpgd_httpgd_svg_", devnum, page, width, height, PACKAGE = "httpgd")
}

httpgd_remove_ <- function(devnum, page) {
  .Call("_httpgd_httpgd_remove_", devnum, page, PACKAGE = "httpgd")
}

httpgd_clear_ <- function(devnum) {
  .Call("_httpgd_httpgd_clear_", devnum, PACKAGE = "httpgd")
}
