# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

httpgd_ <- function(host, port, bg, width, height, pointsize, aliases, recording, cors, token) {
    .Call(`_httpgd_httpgd_`, host, port, bg, width, height, pointsize, aliases, recording, cors, token)
}

httpgd_state_ <- function(devnum) {
    .Call(`_httpgd_httpgd_state_`, devnum)
}

#' Dummy graphics device for debug purposes.
#'
#' @export
dummygd_ <- function() {
    .Call(`_httpgd_dummygd_`)
}

