# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

httpgd_ <- function(host, port, bg, width, height, pointsize, aliases, cors, token, webserver, silent) {
    .Call(`_httpgd_httpgd_`, host, port, bg, width, height, pointsize, aliases, cors, token, webserver, silent)
}

httpgd_state_ <- function(devnum) {
    .Call(`_httpgd_httpgd_state_`, devnum)
}

httpgd_random_token_ <- function(len) {
    .Call(`_httpgd_httpgd_random_token_`, len)
}

httpgd_svg_ <- function(devnum, page, width, height) {
    .Call(`_httpgd_httpgd_svg_`, devnum, page, width, height)
}

httpgd_remove_ <- function(devnum, page) {
    .Call(`_httpgd_httpgd_remove_`, devnum, page)
}

httpgd_clear_ <- function(devnum) {
    .Call(`_httpgd_httpgd_clear_`, devnum)
}

