# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dummygd_ <- function() {
    .Call(`_httpgd_dummygd_`)
}

httpgd_ <- function(host, port, bg, width, height, pointsize, aliases) {
    .Call(`_httpgd_httpgd_`, host, port, bg, width, height, pointsize, aliases)
}

httpgd_playDisplayList <- function() {
    invisible(.Call(`_httpgd_httpgd_playDisplayList`))
}

